stellarwp/kadence-blocks

- src/blocks/row-layout/edit.js
There was a mislabeled control in the inspector settings of the Row Layout block. This PR fixes it.
> Fixed typo in Row Layout edit.js

- src/blocks/advanced-heading/editor.scss
In the Tabs block settings or blocks with kt-size controls, under controls such as Title Spacing, after selecting 'Linked' button, the second button 'Individual' becomes inaccessible due to positioning/z-index issue. Adding position:relative to solve the problem.
> button.components-button.kt-size-btn position

- .gitignore
- dist/blocks.editor.build.css
- dist/blocks.style.build.css
- package-lock.json
- src/blocks/column/block.js
- src/blocks/row-layout/block.js
Hi,
I've just recently added Block Navigation toolbar on my [EditorsKit](https://wordpress.org/plugins/block-options/) plugin. I think this will be of great help on user navigation when both plugins are activated. The toolbar will only be shown on blocks with multiple inner blocks capability.
Here's how it works:
Let me know your thoughts.
Thanks,
Jeffrey
> Add support for EditorsKit navigator toolbar

- src/hex-to-rgba.js
Solves the problem of applying the opacity onto the colors from the Gutenberg color palette, when the color palette contains a CSS Custom Property. It expects the css variable to be defined on the `:root` element.
How to test:
Apply this palette to Gutenberg:
```php
add_theme_support( 'editor-color-palette', [
[
'name' => __( 'Palette Color 1', 'blocksy' ),
'slug' => 'palette-color-1',
'color' => 'var(--paletteColor1)',
],
[
'name' => __( 'Palette Color 2', 'blocksy' ),
'slug' => 'palette-color-2',
'color' => 'var(--paletteColor2)',
],
[
'name' => __( 'Palette Color 3', 'blocksy' ),
'slug' => 'palette-color-3',
'color' => 'var(--paletteColor3)',
],
[
'name' => __( 'Palette Color 4', 'blocksy' ),
'slug' => 'palette-color-4',
'color' => 'var(--paletteColor4)',
],
[
'name' => __( 'Palette …
```
> feat($general): support themes with variables in their color palette

- src/blocks/column/copy-paste-style.js
This is regarding a customer ticket. 
If the user has specifically set the margin or padding value to 0 they might be overriding a global style. In which case they would want these values retained when copying/pasting styles from one column to another.
> Copy values of (int) 0 when copying padding & margin settings

- dist/class-kadence-blocks-frontend.php
Wasn't calling `render_image_css_head`
> Include image.style.build.css in head tag instead of end of body tag

- dist/class-kadence-blocks-frontend.php
Imagify replaces the `img` tag with a `picture` tag that has the classes of the previous img tag. Some attributes aren't applied properly since they are currently being applied to the `picture` tag in the current setup
> Image block support for Imagify picture tags

- dist/form-ajax.php
A small and simple implementation which makes it possible to send the remote IP of the form submitter along with the form/email message to the website owner etc.
It was one of the few features I missed in the  Kadence Form Block, which does however make it (alot) easier to block IP's etc from the site when abuse is detected.
I have seen this implemented in several other 'form plugins' for Wordpress, however with this small 'feature' implemented in the Kadence Form Block it would not be needed at all for me to use any other plugin :)
> Add option to send remote IP using a hidden field on (email) forms.

- src/blocks/form/edit.js
- src/helpers/helpers.js
Any objections to moving `getPreviewSize` function to its own helper file? I've implemented it in this PR
[src/helpers/helpers.js](https://github.com/oakesjosh/kadence-blocks/blob/fc8163d854251f0425c96a1119c5f45a9e6c6d20/src/helpers/helpers.js)
This PR fixes responsive previews for 
- label font size
- label line height
- style font size
- style line height
- submit font size
- submit line height
> [Form] Fix inaccurate preview of responsive changes 

- dist/class-lottieanimation-post-rest-api.php
From HelpScout ticket #24639
"Lottie files" from lordicon.com often have new line characters in their strings which wen't playing nicely with our parsing
> Replace new line characters with spaces in lottie json

- src/blocks/advanced-btn/edit.js
This panel shouldn't have had an index appended to its key
> Fix KadencePanelBody error on advanced button

- src/blocks/rowlayout/style.scss
PR-ing this since it's a row layout CSS change. This is adding back two CSS properties that were [set previously](https://github.com/kadencewp/kadence-blocks/blob/new-image-block/src/blocks/row-layout/style.scss#LL24C17-L24C17). 
Issue: Section block within a row layout has a -200 z-index. Section was not visible on front end. 
This is more of a backwards compatibility fix. We could adjust the starter template to work properly. Sections with a negative z-index that are outside of row layout will still not be visible on the front end.
ClickUp ID: #867780m2f
> Support negative z-index on sections

- src/plugins/prebuilt-library/toolbar-library.js
addresses: https://app.clickup.com/t/863g28vdu
The problem is that we're using the editor plugin system's render method to append a button to the toolbar. 
I think the editor plugin system is linked more to the sidebar? In any case, it's not really in sync with the header toolbar. There's nothing promising that the toolbar's rendering will cause a re-render of an editor plugin. and so our button can get lost that way.
According to my testing, our plugin runs it's render, checks for the existence of the toolbar element, and renders the button as it should.
Then almost immediately after, the toolbar element re-renders itself. Thus the button is no longer appended. Our plugin does not re-run it's render at this point, only when it's given a reason to like the screen size changing or …
> Hacky solution to make doubly sure the design library button has rendered

- src/blocks/rowlayout/style.scss
A good example is setting a row with two columns to min-height 100vh, set Inner Column Height 100%
then try to set the background on one of the columns. the background won't be 100vh, it will be the max-content of one of the columns.
This css attempts to resolve that issue and keep the max-content behavior when the columns collapse or go into row layout.
> fixes columns set to 100% of the row height being limited by their max-content height

- src/packages/components/src/measurement-range-control/responsive.js
- src/packages/helpers/src/index.js
- src/packages/helpers/src/spacing-utilities/index.js
Addresses: https://app.clickup.com/t/865buf7ze
----
TLDR: I fixed and improved custom/option toggling in the responsive measure range control. This needs more testing.
----
So the issue with values disappearing in the responsive measure range control was two parts:
First, we are converting option values (xs, md, etc) to custom values (12, 9, etc) whenever the custom toggle is switched. This conversion always takes place and if any values can't be converted, they're cleared back to ''. 
Second, we only (and always) perform this conversion on the desktop values.
So what was happening was that someone could enter in some desktop custom values, then switch to tablet, then click the custom toggle. This triggered a conversion on the desktop custom values to option values. If they didn't …
> Upgrading the conversion functionality of the responsive measure range

- includes/blocks/class-kadence-blocks-column-block.php
- includes/class-kadence-blocks-frontend.php
addresses: https://app.clickup.com/t/8677kzz4k
Post content that gets passed into css and html build processes that happen after the 'render_callback' entry point are appropriately filtered by wp offload media
but for the row/column layout (and potentially others), they have image attributes that get output through a different process, namely the 'frontend_build_css' function
This function gets block content with the parse_blocks function and its post content straight from the global $post object. Straight from the tap so speak. So wp offload media doesn't have the chance to filter it.
Adding in their custom filter higher up in the chain when we initially grab post content resolves issues where the correct url is not used when outputting these attributes.
> Adding filter to make sure wp offload media runs on all content that would render css

- includes/blocks/class-kadence-blocks-form-block.php
According to [this article](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields), most browsers no longer respect the autocomplete="off" attribute. I've implemented the [proposed unofficial approach](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password) of using `autocomplete="new-password"`, which browsers do not autofill or save. 
Although I was unable to reproduce the autocomplete issue using Chrome or Firefox's native autofill, it did occur when using 1Password and LastPass. I've added the `data-1p-ignore` and `data-lpignore` attributes to address that problem.
I can send a zip of these …
> Fix autofill issue when using basic honeypot

- src/plugins/prebuilt-library/ai-wizard/components/image-select/index.js
- src/plugins/prebuilt-library/ai-wizard/components/slider/slider.js
- src/plugins/prebuilt-library/ai-wizard/index.js
- src/plugins/prebuilt-library/ai-wizard/kadence-ai-wizard.js
- src/plugins/prebuilt-library/pattern-library.js
https://www.loom.com/share/1d13684df60d4a95a41bbed358a098a8
- Adds the ability to open the AI Modal and see only the photography UI.
- Changes `wp.media` request to open in `add` mode, allowing the user to select multiple images without holding the CTRL key.
- Adjusts the clamp values on images within the AI Modal slideshow for better small-screen display.
> AI Modal Feature

- includes/class-kadence-blocks-prebuilt-library-rest-api.php
Updates all Prophecy post requests to send as a JSON body. This fixes a bug where if the any of the fields (company, mission etc...) had an `&` symbol, it was never urlencoded. All of these were previously sent as a query string, so when it came time for WordPress on the Content server to get the parameters, anything after the unescaped `&` was considered a variable and not the actual content.
This is a much safer way to send data as we'll also never hit max URI length limits etc...
> Prophecy REST request improvements / bug fixes

- src/plugins/prebuilt-library/ai-wizard/components/autocomplete/autocomplete.js
The custom 'Add' UI was failing to appear when manually deleting input values and immediately search again.
Reset state used to determine visibility of the 'Add' UI on key-down.
> Fix: Algolia 'Add' industry behavior

- includes/class-kadence-blocks-css.php
On the SolidWP site, we were experiencing a fatal error due to the `render_gap()` attributes for icons being set to empty arrays during `build_css()` of the icon block.
> Prevent fatals from being thrown if the gap_size indices are arrays

- includes/analytics/class-analytics.php
- includes/class-kadence-blocks-prebuilt-library-rest-api.php
- kadence-blocks.php
Most of the plugin's registered REST routes were manually configuring the `X-Prophecy-Token` header. This reduces that code repetition and provides a single point where those values can be modified.
> Simplify & Standardize X-Prophecy-Token creation for plugin REST API endpoints

- src/plugins/prebuilt-library/pattern-list.js
Further inspecting the "Pattern added to Page" event, Donaldo helped me realize that non-ai patterns do not have a context. The event was incorrectly sending the AI-based context for non-ai patterns.
> Stop sending context values with non-AI patterns

- includes/class-kadence-blocks-ai-events.php
- src/blocks/advancedheading/ai-text/ai-text.js
This adds functionality to capture events when users request AI content within the **Text (Adv)** block.
> Add Events for AI Inline Complete

- src/plugins/prebuilt-library/ai-wizard/context/kadence-ai-provider.js
- src/plugins/prebuilt-library/ai-wizard/kadence-ai-wizard.js
This adds some additional state to the AI Wizard to track if a user has officially completed it. Complete meaning that they clicked the primary "Generate" button on the last step and generated all the contexts.
> Only send AI Wizard Completed event once complete

- includes/class-kadence-blocks-prebuilt-library-rest-api.php
This adds Context Generation Failed and Requested along with the existing Context Generation Completed event:
https://github.com/stellarwp/kadence-blocks/blob/dfda3d8ce2ae07a9a5a4371af214e45c95328aa0/includes/class-kadence-blocks-prebuilt-library-rest-api.php#L1094
> [KADEN-293] [KADEN-294] Send failed and requested events

- src/blocks/column/edit.js
KAD-1982
Issue: Drag a "full width" aligned section into an existing row layout. When in a row layout, we hide align settings for sections.
Proposal: We unset the align on the section if this happens. We already defer alignment to the parent row in this situation.
> Unset align on section when moved into row layout

- includes/class-kadence-blocks-ai-events.php
- src/plugins/prebuilt-library/ai-wizard/context/kadence-ai-provider.js
- src/plugins/prebuilt-library/ai-wizard/kadence-ai-wizard.js
- src/plugins/prebuilt-library/ai-wizard/pages/photography.js
> **NOTE:** I didn't have time to test a brand new wizard run, just an existing one and updating via the design library.
- If a collection wasn't custom (aka premade), it would be an empty string in the event payload.
- This event would previously send the user's old collection, because it was firing before saving was complete.
- This properly tracks changed collections each time a user changes it either through the Wizard, or through: _Design Library > Settings Icon > Update Design Library Images_.
- The event will now tell us if it's a custom collection.
- I wasn't sure why [handleSave() ](https://github.com/stellarwp/kadence-blocks/compare/bugfix/KAD-1961/collection-updated-event?expand=1#diff-3f260d3b955791cd26c02f4447e0032530d5546fa94b033c702d86704702b031L146)is called even after …
> [KAD-1961]: Properly track collection_updated events

- includes/advanced-form/advanced-form-submit-actions.php
- includes/templates/form-email.php
[KAD-1847](https://stellarwp.atlassian.net/browse/KAD-1847)
...
[KAD-1847]: https://stellarwp.atlassian.net/browse/KAD-1847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove magic quotes from email body

- src/blocks/column/edit.js
[KAD-2321](https://stellarwp.atlassian.net/browse/KAD-2321)
...
[KAD-2321]: https://stellarwp.atlassian.net/browse/KAD-2321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change fallback for locking inner blocks in row layout

- includes/resources/App.php
- includes/resources/Health/Health_Provider.php
- includes/resources/Health/Required_Function_Verifier.php
- includes/resources/Image_Downloader/Image_Downloader_Provider.php
- includes/resources/Notice/Notice_Handler.php
- tests/_support/Classes/TestCase.php
- tests/wpunit/Resources/Notice/NoticeHandlerTest.php
1. We no longer use the Monolog error logger if the `error_log` function is disabled, preventing a fatal error for an undefined function.
2. Adds a Health Check system, with a PHP function checker, this way, logs aren't just silently writing no where when debugging needs to happen and will warn the user.
3. If any PHP functions we define are disabled, notices will appear on the Kadence Settings Page, which support can now ask users to visit to verify there are no notices displayed there.
> Note: If you have better wording for the notices, please let me know.
🎫  #[Jira Ticket]
https://ithemeshelp.zendesk.com/agent/tickets/589622
> Feature: add health check

- composer.json
- Fixes `composer install` Strauss path issues for Windows users by updating to Strauss 0.19.1
- Adds `composer strauss-clean` command to remove your existing strauss.phar so an update can happen.
> Fix `composer install` Strauss path issues for Windows users

- wpml-config.xml
This allows to translate Alt and Captions strings for Advanced Gallery blocks.
Initially, it was reported here:
https://wpml.org/de/forums/topic/uebersetzung-von-meiner-wodpress-seite/
🎫  #[Jira Ticket]
...
- [] Is the issue from the ticket solved? (If not, why?)
> Advanced Gallery blocks: Making Alt and Captions translatable

- includes/blocks/class-kadence-blocks-infobox-block.php
🎫  #[Jira Ticket]
[https://stellarwp.atlassian.net/browse/KAD-2926](https://stellarwp.atlassian.net/browse/KAD-2926)
...
> KAD-2926 height/width removed from kadence-info-box-image-intrisic

- includes/settings/class-kadence-blocks-settings.php
🎫  https://ithemeshelp.zendesk.com/agent/tickets/607623
[Slack thread](https://lw.slack.com/archives/C05D4PKNZ9V/p1715893408303279)
This disables the remote auth license checks on the Kadence home page if the user has defined `define( 'KADENCE_BLOCKS_AI_DISABLED', true );` in their wp-config.php.
> :warning:  As this forces [Authorization to false for the frontend](https://github.com/stellarwp/kadence-blocks/blob/8d0ab936c964e7f44b8d6f6d30106542eb726814/includes/settings/class-kadence-blocks-settings.php#L782), I am not sure if that used outside of AI at all, but if it is, it could potentially lead to some regressions. However, given this same logic applies in the [block editor assets](https://github.com/stellarwp/kadence-blocks/blob/975f84cd55bfeae9ae3872df3bbcdc3a01f86852/includes/class- …
> Don't perform an authorization check on Kadence Home if AI is disabled

- includes/resources/Image_Downloader/Image_Downloader_Provider.php
> :rotating_light: If this code has been copied and pasted into other Kadence plugins, it should be applied there too.
I wasn't properly setting the log level for the error log handler, this fixes it so it can be properly customized by the `kadence_blocks_image_download_log_level` filter.
> BUG FIX: Ensure we set the log level on the error log handler as well

- includes/blocks/class-kadence-blocks-search-block.php
- readme.txt
- src/blocks/search/block.json
[https://stellarwp.atlassian.net/browse/KAD-4123](https://stellarwp.atlassian.net/browse/KAD-4123)
The block.json didn't declare the "label" attribute, so the aria label wasn't saving in the backend. Additionally, the frontend did not include the aria-label in the HTML. This fix lets the aria label get saved and adds it to the frontend HTML if it exists.
> bugfix/KAD-4123 Adv Search > Aria Label setting not working

- includes/blocks/class-kadence-blocks-progress-bar-block.php
aria-labels are not allowed on elements without a role. Add the note role to the progress bar if using one. https://stellarwp.atlassian.net/browse/KAD-4303
See https://stellarwp.atlassian.net/browse/KAD-3917 for more background on why we don't use the progress bar role
> Add the note role to progress bar if using aria-label

- includes/blocks/class-kadence-blocks-search-block.php
- readme.txt
[https://stellarwp.atlassian.net/browse/KAD-4411](https://stellarwp.atlassian.net/browse/KAD-4411)
I opted to remove the label and add a default aria label instead. 
Now, there is always an aria-label and no need for an html label. If the user neglects to add a custom aria label, the aria label reads as “Search” for both the standard and modal input fields.
> KAD-4411 removed label and added default aria-label for search block

- src/extension/stores/index.js
This doesn't address the root cause, which I couldn't find, but puts a suitable bandaid on for the widgets page. https://stellarwp.atlassian.net/browse/KAD-4327
Note that I couldn't consistently reproduce the issue. Some of my sites had it and others didn't.
> fixing an issue with the widgets editor and preview device selecting.

- includes/navigation/class-kadence-navigation-cpt.php
- readme.txt
…PT_Controller to 'insert'
[https://stellarwp.atlassian.net/browse/KAD-4564](https://stellarwp.atlassian.net/browse/KAD-4564)
Changed the template lock for the Navigation CPT to 'insert' instead of all. This stops the warning about the content not matching the template assigned to the post.
> KAD-4564_navigation_warning

- readme.txt
- src/blocks/advancedgallery/editor.scss
[https://stellarwp.atlassian.net/browse/KAD-4663](https://stellarwp.atlassian.net/browse/KAD-4663)
custom link options for mosaic gallery did not have the correct styles and the input field wasn't showing when an image was selected. This fix adds styles so the input field is visible in the editor.
> KAD-4663 Add custom link options styling for mosaic gallery
