stellarwp/kadence-blocks

src/blocks/row-layout/style.scss
Was missing the styles for 60-40 columns.
=> Added styles for 60-40 columns

dist/class-kadence-blocks-frontend.php, src/blocks/column/block.js, src/blocks/column/edit.js
Addition of 'BorderRadius' range control to the column block
=> Add 'BorderRadius' property to columns

dist/settings/class-kadence-blocks-settings.php
Found advancedgallery misspelled
=> Misspelled block

dist/class-kadence-blocks-frontend.php
This pull request adds a few filters, the minimum amount of them, in order for automatic Toolset Dynamic Sources integration to be allowed for the targeted blocks.
=> Add hooks for automatic Tooslet Dynamic Sources everywhere.

src/blocks/row-layout/edit.js
I found one typo mistake and resolved it.
=> Resolved Typo.

dist/class-kadence-blocks-frontend.php
max-width on mobile CSS is the width of Tablet
HelpScout Ticket 23396
=> Fix accordion inner padding on mobile from also applying to tablet

includes/blocks/class-kadence-blocks-advancedbtn-block.php, includes/blocks/class-kadence-blocks-image-block.php, includes/blocks/class-kadence-blocks-row-layout-block.php
I saw a few references here to files that don't exist while I was comparing 3.0 to pro for the build refactor there.
I updated their links to files that do exist.
=> style reference updates

includes/blocks/class-kadence-blocks-singlebtn-block.php, includes/helper-functions.php
Addresses https://app.clickup.com/t/863ftyk9h
Accomplished via a helper function that other blocks can use if they're in a similar situation.
=> adding aos data attributes to button frontend output

src/blocks/form/editor.scss, src/blocks/form/style.scss
Adresses: https://app.clickup.com/t/3yudkdd
=> styles to move form labels and inputs according to the hAlign attribute

src/assets/js/kt-tabs.js, src/blocks/tabs/save.js
Resolves https://app.clickup.com/t/3xxum56
=> adding tablist role to the tabs block

src/blocks/image/edit.js, src/packages/components/src/border/border-control/index.js, src/packages/components/src/border/border-control/single-control.js, src/packages/components/src/border/responsive-border-control/index.js, src/packages/helpers/src/get-border-style/index.js
This is to support unit inheritance / control from desktop.
Adjusted necessary files to support this.
=> border controls are now default unitless

composer.json
Just a couple of small tweaks.
=> Remove strauss as a dependency and set PHP version

src/blocks/accordion/editor.scss
h tags now match from editor to frontend in the accordion block
=> bug fix to Accordion block

includes/blocks/class-kadence-blocks-accordion-block.php, src/blocks/accordion/block.json, src/blocks/accordion/edit.js
added setting to allow users to set text color to all inner content in one accordion.
=> Accordion additions 

src/packages/icons/src/accordion/index.js, src/packages/icons/src/tabs/index.js, src/packages/icons/src/vtabs/index.js
@kadencewp  svg icons are in but still need TLC
=> replaces old tab icons in editor panelpanel

src/blocks/infobox/block.json, src/blocks/infobox/edit.js, src/blocks/infobox/save.js
ClickUp https://app.clickup.com/t/865bthx8f
=> Allow non-header tag for Info box title

includes/blocks/class-kadence-blocks-lottie-block.php, src/blocks/lottie/block.json, src/blocks/lottie/edit.js, src/blocks/lottie/index.js, src/blocks/lottie/style.scss
addresses: https://app.clickup.com/t/8677tjum2
=> adding option to provide a fixed ratio to lottie block to prevent layout shift

includes/class-kadence-blocks-svg.php
Such as dynamic content images.
Addresses: https://app.clickup.com/t/3rxj2qc
=> A fix for svg dimensions gathered with wp_get_attachment_src.

src/blocks/advanced-form/fields/file/block.json
=> Add missing attribute for error message in the file field

includes/class-kadence-blocks-prebuilt-library-rest-api.php, src/plugins/prebuilt-library/ai-wizard/hooks/use-database.js, src/plugins/prebuilt-library/ai-wizard/kadence-ai-wizard.js, src/plugins/prebuilt-library/pattern-library.js
This adds functionality required to send the "AI Wizard Completed" Event to analytic services.
=> [KADEN-286]: AI Wizard Completed Event

includes/class-kadence-blocks-ai-events.php, includes/class-kadence-blocks-prebuilt-library-rest-api.php, src/extension/analytics/send-event.js, src/plugins/prebuilt-library/ai-wizard/kadence-ai-wizard.js, src/plugins/prebuilt-library/data-fetch/get-async-data.js, src/plugins/prebuilt-library/pattern-library.js, src/plugins/prebuilt-library/pattern-list.js
This improves the locations of Analytics specific functionality so that it's all encapsulated within a single class. It also simplifies calling the `sendEvent()` method in JS.
=> AI Analytics Functionality Refactor

includes/blocks/class-kadence-blocks-infobox-block.php
[KAD-1420](https://stellarwp.atlassian.net/browse/KAD-1420)
[KAD-1420]: https://stellarwp.atlassian.net/browse/KAD-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add specificity to selector

src/blocks/advancedgallery/editor.scss, src/blocks/advancedgallery/gallery-image.js
[KAD-1778](https://stellarwp.atlassian.net/browse/KAD-1778)
[KAD-1778]: https://stellarwp.atlassian.net/browse/KAD-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Give min-width to gallery image options

src/plugins/prebuilt-library/assets/css/pattern-filters.scss, src/plugins/prebuilt-library/editor.scss, src/plugins/prebuilt-library/pattern-library.js, src/plugins/prebuilt-library/pattern-list.js
- Adds style filters into the pattern list in the design library
http://p.tri.be/i/2GDScH
=> Design library style filters

includes/class-kadence-blocks-ai-events.php, src/blocks/advancedheading/ai-text/ai-text.js
[KADEN-292](https://moderntribe.atlassian.net/browse/KADEN-292)
[KADEN-292]: https://moderntribe.atlassian.net/browse/KADEN-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KADEN-292] Add AI Inline Requested Event

includes/blocks/class-kadence-blocks-row-layout-block.php, src/blocks/rowlayout/style-controls.js
[KAD-1817](https://stellarwp.atlassian.net/browse/KAD-1817)
[KAD-1817]: https://stellarwp.atlassian.net/browse/KAD-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove video poster option when YouTube and Vimeo are selected

includes/blocks/class-kadence-blocks-infobox-block.php
[KAD-1853](https://stellarwp.atlassian.net/browse/KAD-1853)
[KAD-1853]: https://stellarwp.atlassian.net/browse/KAD-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix / infobox font size in tablet and mobile

includes/blocks/class-kadence-blocks-singlebtn-block.php
[KAD-1832](https://stellarwp.atlassian.net/browse/KAD-1832)
[KAD-1832]: https://stellarwp.atlassian.net/browse/KAD-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix / Button transition not working properly

src/packages/components/src/typography/typography-control/index.js
[KAD-1775](https://stellarwp.atlassian.net/browse/KAD-1775)
[KAD-1775]: https://stellarwp.atlassian.net/browse/KAD-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add default font weight value

includes/blocks/class-kadence-blocks-column-block.php
[KAD-242](https://stellarwp.atlassian.net/browse/KAD-2421)
[KAD-242]: https://stellarwp.atlassian.net/browse/KAD-242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FIx vertical alignment for row layout inner columns

includes/blocks/class-kadence-blocks-column-block.php, src/blocks/column/editor.scss
[KAD-2486](https://stellarwp.atlassian.net/browse/KAD-2486)
...
[KAD-2486]: https://stellarwp.atlassian.net/browse/KAD-2486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix / section vertical align

src/blocks/advancedbtn/edit.js
Came across this while looking at something else. Looking for some extra eyes and testing.
KAD-2643
=> Remove higher order components from advancedbtn block

src/blocks/column/edit.js
[KAD-1927](https://stellarwp.atlassian.net/browse/KAD-1927)
...
[KAD-1927]: https://stellarwp.atlassian.net/browse/KAD-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/section vertical gap comming from 3.1.26

src/blocks/header/children/components/child-container/index.js, src/blocks/header/children/off-canvas/edit.js, src/blocks/navigation-link/edit.js
=> Nav menu performance

includes/blocks/class-kadence-blocks-navigation-block.php, includes/blocks/class-kadence-blocks-navigation-link-block.php, includes/navigation/class-kadence-navigation-cpt.php, src/blocks/navigation-link/components/backend-styles/index.js, src/blocks/navigation/components/backend-styles/index.js, src/blocks/navigation/edit-inner.js, src/blocks/navigation/style.scss
to match controls for the nav item
Also cleaning up some styling around nav link alignment not applying correctly
🎫  https://stellarwp.atlassian.net/browse/KAD-3694
...
=> adding link alignment controls to the parent navigation block

includes/blocks/class-kadence-blocks-header-block.php
https://stellarwp.atlassian.net/browse/KAD-4330
=> Fixing issue with anchor's on header blocks.

includes/blocks/class-kadence-blocks-progress-bar-block.php, src/blocks/progress-bar/edit.js, src/blocks/progress-bar/editor.scss
Some are specific to alignment inside sections
https://stellarwp.atlassian.net/browse/KAD-4350
=> Some fixes around progress bar max width and alignment.

includes/blocks/class-kadence-blocks-advancedgallery-block.php, readme.txt, src/blocks/advancedgallery/style.scss
[https://stellarwp.atlassian.net/browse/KAD-4483](https://stellarwp.atlassian.net/browse/KAD-4483)
mosaic gallery items are divs now instead of list items.
=> KAD-4483 mosaic items no longer list items

includes/blocks/class-kadence-blocks-icon-list-block.php, readme.txt, src/blocks/iconlist/style.scss
[https://stellarwp.atlassian.net/browse/KAD-4552](https://stellarwp.atlassian.net/browse/KAD-4552)
If Icon List listMargin isn't set, add a default in the frontend styles.
=> KAD-4552_icon_list_bottom_margin

includes/init.php, src/blocks/navigation-link/components/backend-styles/index.js, src/blocks/navigation/edit.js
This addresses default width for mega menus and sub navigations not appearing. https://stellarwp.atlassian.net/browse/KAD-4517
=> Fixing some issue around directly editing navigations with mega menus.

readme.txt, src/blocks/column/edit.js
[https://stellarwp.atlassian.net/browse/KAD-4771](https://stellarwp.atlassian.net/browse/KAD-4771)
Updated the selector for the background hover colors. The frontend works as expected so the edit.js file was updated to match the frontend selector.
=> KAD-4771 Update selector for background hover color.

src/blocks/header/edit-inner.js
https://stellarwp.atlassian.net/browse/KAD-4948
=> core range control needed a different property name for resetting
